# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy the contents of the index.html file to the default Nginx web root directory
COPY index.html /usr/share/nginx/html

# Expose port 80 to allow external access to the web server
EXPOSE 80
